#!/bin/bash

#SBATCH --job-name=mpi
##SBATCH --output=mpi.txt
#SBATCH -N 2 # number of nodes
##SBATCH -n 15 # number of cores/processes
##SBATCH --distribution=cyclic
#SBATCH --exclusive
##SBATCH --partition=nodo.q  #cluster Wilma
#SBATCH --partition=new-nodo.q  #cluster Wilma++
##SBATCH --partition=aolin.q  #cluster aolin laboratori (només funciona per la nit)

module add gcc/12.1.1
module load openmpi/4.1.1

mpicc -Ofast main.c GameLogic/boardDisplay.c GameLogic/gameFunctions.c MLContent/alphaBetaAlgo.c MLContent/minimaxAlgo.c -o connect4 -lm -lmpi


for PROC in 2 4
do
    echo "OMP_NUM_THREADS: Sequential"
    echo "MPI_NUM_PROCS: $PROC"
    echo "Depth: 8"

    ## export OMP_NUM_THREADS=1

    mpirun -np $PROC ./connect4 8

    echo "---------------------------------------"

done